Fix unused comment error from mypy
This comment is likely to be unnecessary:

```pytb
src/magicgui/schema/_guiclass.py:260: error: Unused "type: ignore" comment  [unused-ignore]
                signals = {k: events[k] for k in events}  # type: ignore
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 1 source file)
```