Add Separator to ComboBox (#638)
* Add Separator to ComboBox

* Fix unused comment error from mypy

This comment is likely to be unnecessary:

```pytb
src/magicgui/schema/_guiclass.py:260: error: Unused "type: ignore" comment  [unused-ignore]
                signals = {k: events[k] for k in events}  # type: ignore
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 1 source file)
```

* Add Separator tests

* Refactor Separator into singleton sentinel

* Add Separator: choices exclude separator items

Co-authored-by: Talley Lambert <talley.lambert@gmail.com>

* Fix duplicate choice names in ipynb Dropdown, add Separator support

- Fix #639
- Note that `_mgui_set_choice()` is not used

* Add Separator: ipynb compatibility

Revert the behaviour change of ipynb duplicate items

* Add Separator: improve test

Co-authored-by: Talley Lambert <talley.lambert@gmail.com>

* Add Separator: hide separator items from users

* Fix ipynb backend `_mgui_set_choice()`

---------

Co-authored-by: Talley Lambert <talley.lambert@gmail.com>